# https://github.com/yannart/docker-compose-demo
# https://docs.docker.com/samples/httpd/#httpdalpine
# https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix

version: '3'

services:
  web:
    build: .
    container_name: "ppl"
    env_file:
      .env
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - DOCKER=docker
    volumes:
      - ".:/home/app"
    command: npm run dev
    ports:
      - "8000:8000"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    restart: always
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  mongo-seed:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/home/app/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "./data/db:/home/app/data/db"
    command: mongorestore --drop  --quiet --host mongodb --port 27017 --db ppl /home/app/data/db

  # apache:
  #   image: httpd:2.4
  #   volumes:
  #     - "./apache2:/etc/apache2"
  # command: a2enmod proxy rewrite proxy_http proxy_wstunnel
